### PR TITLE
Final changes to Members Only Project

### PR DESCRIPTION
**Pull request by phfdonda**
**Hi!** 
This is the PR for the Members Only! Project. In it we:
- Created a Rails app that emulates a blog;
- Configured in such a way that it requires the user to be logged in to post;
- Set up authentication logic to make sure only members are able to see the authorship of posts;
- Also added requirements for editing and deleting posts: only the author can change their posts;
- Made sure that non-members can still read the posts, even though not the name of the authors.

We hope everything is in order. Let us know if we could improve the project in any way!

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Required❌
# 🙋‍♂️ Team!!!
#### You have done a great job on this one, here are some tiny issues to address
* [ ] It creates the application routes using resources :posts, only: [:new, :create, :index] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) 
The ```resources: posts``` will capture routes mapped to the obsolete actions mentioned above thereby creating obsolete routes, let strive to keep clean code all the time.
* [ ] ```@posts = Post.all.order('created_at DESC')``` queries that hit the DB directly should be made in the model, not in the controller. this could be handle by using the ```default_scope``` 
(Where Do I Put My Code?)[http://codefol.io/posts/Where-Do-I-Put-My-Code/]
The show and edit action of the post controller are obsolete(empty). Why commit them?
> Kindly address the issue with the conflict on the branch, I believe it is coming from the readme file.
### That is it, kindly make these changes and submit a re-review🙇‍♂️.
#### Happy coding👨‍💻.
#### Addo Forison

**Comment by phfdonda** [comment]
Hi, Forison!
Thank you again for your great reviews! I learned how to use a scope now, that was great! I changed the controllers files and moved the database queries to the models files.
I also removed the unnecessary and empty methods from the controllers. 
I hope that's good enough, let me know otherwise!

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required
### Hello team :wave: 
I think we misunderstood the review by @Forison 

**REQUIRED**
* According to [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) on Odin, we should have `resources :posts, only: [:new, :create, :index]` in our routes. 
This means that we should only have `new`, `create`, and `index` actions in our post controller. This will ensure that we only have the specified routes instead of all the seven restful routes generated by default when we don't specify like in `resources :posts`. 
The main thing is to get rid of unused routes and specify the only one we need.

I hope this clears thing up.

**After working on the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by Maclenn77** [comment]
Hi! 

Sorry by the misunderstanding. Solved the problems pointed out.

**Comment by uryelah** [comment]
Hi **Pedro Donda & J. P. Pérez Tejada Ladrón de Guevara**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this project, I specially like how you handled the RegistrationsController creation. Great code separation.

This is good to approve, but as an optional requirement and reminder for the next projects try to refactor the conditional statement inside the posts/index view.:
` <% if member_signed_in? %>...`
It's usually best to put any view logic(conditionals, loops, etc) inside helper methods. 

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
